#!/usr/bin/env python3

import rospy
import actionlib
from rbx1_scripts.msg import executePositionGoalAction, executePositionGoalFeedback, executePositionGoalResult
from geometry_msgs.msg import Pose

if __name__ == '__main__':
    rospy.init_node('position_goal_client')

    # Create an action client for the "executePositionGoal_as" action server
    client = actionlib.SimpleActionClient("executePositionGoal_as", executePositionGoalAction)
    client.wait_for_server()

    # Prompt the user for the goal coordinates
    position_goal = Pose()
    position_goal.position.x = float(input('Enter the x-coordinate of the goal position: '))
    position_goal.position.y = float(input('Enter the y-coordinate of the goal position: '))
    position_goal.position.z = float(input('Enter the z-coordinate of the goal position: '))


    # Send the goal to the action server and wait for a result
    client.send_goal(position_goal)
    client.wait_for_result()

    # Print the result
    result = client.get_result()

    rospy.loginfo('Result: {}'.format(result))
